"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _box_stats_panel from './box-stats-panel.bones.json'
import _box_grid from './box-grid.bones.json'
import _item_grid_wishlist from './item-grid-wishlist.bones.json'
import _billing_settings from './billing-settings.bones.json'
import _item_grid_collection from './item-grid-collection.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.08)","darkColor":"rgba(255,255,255,0.08)","animate":"pulse"})

registerBones({
  "box-stats-panel": _box_stats_panel,
  "box-grid": _box_grid,
  "item-grid-wishlist": _item_grid_wishlist,
  "billing-settings": _billing_settings,
  "item-grid-collection": _item_grid_collection,
})
