"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _box_stats_panel from './box-stats-panel.bones.json'
import _box_grid_card from './box-grid-card.bones.json'
import _item_grid_collection_card from './item-grid-collection-card.bones.json'
import _item_grid_wishlist_card from './item-grid-wishlist-card.bones.json'
import _search_results_card from './search-results-card.bones.json'
import _value_graph from './value-graph.bones.json'

configureBoneyard({"color":"hsl(var(--muted))","darkColor":"hsl(var(--muted))","animate":"shimmer","shimmerColor":"hsl(var(--accent))","darkShimmerColor":"hsl(var(--accent))","speed":"1.9s","shimmerAngle":105})

registerBones({
  "box-stats-panel": _box_stats_panel,
  "box-grid-card": _box_grid_card,
  "item-grid-collection-card": _item_grid_collection_card,
  "item-grid-wishlist-card": _item_grid_wishlist_card,
  "search-results-card": _search_results_card,
  "value-graph": _value_graph,
})
